---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks:    

    - name: Use specific var file
      include_vars:
      vars:
        params:
          files:
            - "vmw_vms.yml"
          paths:
            - "vars/group_vars/{{lab_name}}"

    - name: Deploy the lab cluster on VMware environment
      include: deploy_vmware_cluster.yml
      when: 
        - action == "create"

    - name: Destroy the lab cluster on VMware environment
      include: destroy_vmware_cluster.yml
      when: 
        - action == "destroy"