---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks:     

    - name: Deploy the openshift cluster on VMware environment
      include: deploy_vmware_cluster.yml
      when: 
        - action == "create" 
        - labs == "{{ lab_name }}""
      loop: "{{ labs }}"

    - name: Destroy the openshift cluster on VMware environment
      include: destroy_vmware_cluster.yml
      when: 
        - action == "destroy"