---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks:    

    - name: Deploy the lab cluster on VMware environment
      import_tasks: deploy_vmware_cluster.yml
      when: 
        - action == "create"

    - name: Destroy the lab cluster on VMware environment
      import_tasks: destroy_vmware_cluster.yml
      when: 
        - action == "destroy"
