---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks:    

    - name: Use specific var file
      include_vars:
        file: "group_vars/{{lab_name}}/vmw_vms.yml"

    - name: Deploy the lab cluster on VMware environment
      include: deploy_vmware_cluster.yml
      when: 
        - action == "create"

    - name: Destroy the lab cluster on VMware environment
      include: destroy_vmware_cluster.yml
      when: 
        - action == "destroy"