vms:
  - name: lab1-clienta
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.11
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.11
        netmask: 255.255.255.0
        device_type: vmxnet3

  - name: lab1-clientb
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.12
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.12
        netmask: 255.255.255.0
        device_type: vmxnet3

  - name: lab1-serverc
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.13
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.13
        netmask: 255.255.255.0
        device_type: vmxnet3  

  - name: lab1-serverd
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.14
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.14
        netmask: 255.255.255.0
        device_type: vmxnet3

  - name: lab1-servere
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.15
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.15
        netmask: 255.255.255.0
        device_type: vmxnet3

  - name: lab1-serverf
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.16
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.16
        netmask: 255.255.255.0
        device_type: vmxnet3

  - name: lab1-serverg
    esxi_hostname: 10.101.101.12
    disk:
    - size_gb: 30
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01

    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
    
    - size_gb: 10
      type: thin
      datastore: SSD-PCI-01
      
    networks:
      - name: LABSYSTEM_vnet_04
        ip: 172.11.0.17
        netmask: 255.255.255.0
        gateway: 172.11.0.1
        device_type: vmxnet3

      - name: LABSYSTEM_vnet_05
        ip: 172.12.0.17
        netmask: 255.255.255.0
        device_type: vmxnet3

